### ISSUE TITLE
Projectile Lag

### ISSUE THREAD

**Issue by xDidntPot** [dragonfly-tech/dragonfly#420]
### How to reproduce
- Try throwing a projectile (eg. enderpearl, splash potion) while switching hotbar slots quickly, the projectile *sometimes* "lags" and doesn't get thrown.
### Video 
- https://youtu.be/RIxNQhSLlqM

**Comment by DidntPot** [comment]
*(PMMP also had the same issue: https://github.com/pmmp/PocketMine-MP/issues/4168)*
